spring:
  # env
  config:
    import: optional:file:.env.prod[.properties]

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        generate_statistics: false
        open-in-view: false
        cache:
          use_second_level_cache: false

  transaction:
    default-timeout: 30

# logging
logging:
  level:
    org:
      hibernate:
        sql: info

# port
server:
  port: ${SERVER_PORT:8080}
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


jwt:
  secret:${JWT_SECRET} # 반드시 환경변수 통해 시크릿 키 주입