spring:
  application:
    name: weatherwear

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    multipart:
      enabled: true

  jackson:
    time-zone: Asia/Seoul

  lifecycle:
    timeout-per-shutdown-phase: 30s

  config:
    import: optional:file:.env[.properties]

server:
  shutdown: graceful