spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  logging:
    level:
      org:
        hibernate:
          sql: debug  # 개발 환경에서는 SQL 로그를 debug로 설정